source "http://rubygems.org"

gem 'jekyll', '~>1.0'
gem '<%= jekMkd %>'<% if (cssPre === 'sass' || cssPre === 'compass') { %>
gem 'sass', '>=3.2.8'<% } %><% if (cssPre === 'compass') { %>
gem 'compass', '>=0.12.2'<% } %>
gem 'csscss', '~>1.3.1'
