source "http://rubygems.org"

gem 'jekyll', '~>1.3.0'
gem '<%= jekMkd %>'
gem 'csscss', '~>1.3'<% if (cssPre === 'sass') { %>
gem 'sass', '>=3.2'<% } %><%  if (cssPre === 'compass') { %>
gem 'compass', '>=0.12'<% } %><% if (bitters) { %>
gem 'bitters', '>=0.9.2'<% } %>
